# Generated by Django 4.2.5 on 2023-09-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packing1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Packing2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Packing3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('pro_num', models.IntegerField()),
                ('pro_date', models.DateField(blank=True, null=True)),
                ('packing1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packing1')),
                ('packing2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packing2')),
                ('packing3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.packing3')),
            ],
        ),
    ]
